### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hmm'

### ISSUE THREAD

**Issue by godfery** [dingdang-robot/dingdang-robot#1]
2018-03-21 20:34:33,257 dingdang.py[line:175]         ERROR Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 173, in <module>
    app = Dingdang()
  File "dingdang.py", line 95, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/dingdang/client/stt.py", line 66, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/dingdang/client/stt.py", line 60, in get_instance
    instance = cls(**config)
  File "/home/pi/dingdang/client/stt.py", line 152, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'

**Comment by godfery** [comment]
I have solved the question.
I install pocketsphinx 0.1.3 ,  the Decoder method have been changed 
 
https://pypi.python.org/pypi/pocketsphinx
