### ISSUE TITLE
无法播放声音

### ISSUE THREAD

**Issue by calvingit** [dingdang-robot/dingdang-robot#104]
# **确认已寻找过答案**

我已确认在 [Github issue](https://github.com/dingdang-robot/dingdang-robot/issues) 页、[常见问题](https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting)页、[论坛](http://bbs.hahack.com) 中都查找过，没有找到类似问题。我也没有 google / bing/ 百度 / duckduckgo 到相关问题。

# **安装方式**

镜像安装

# **操作系统**

版本是dingdang-2018-07-16

# **问题描述**
一切按照镜像安装的方式修改profile.yml，启动后微信登录，文本发送都正常，可以使用“叮当”唤醒，但是语音播放的时候就报错了，以下几种情况都是一样的：

- 微信语音发送，无法播放
- 邮件读取，无法播放
- 调用网易云歌曲播放，无法播放

具体错误log如下：
```bash
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/pi/dingdang/client/player.py", line 66, in run
    output=True)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid output device (no default output device)
```

`~/.asoundrc`配置如下：

```
pcm.!default {
        type asym
            playback.pcm {
                type plug
                slave.pcm "hw:0,1"
            }
            capture.pcm {
                type plug
                slave.pcm "hw:1,0"
            }
}

ctl.!default {
        type hw
        card 0
}
```

单独使用`arecord`可以录音，使用`aplay`播放也没问题。即使单独写了一个`pyaudio`的例子，也可以录音和播放

# 硬件
树莓派：3B+
音频输入：USB 麦克风
音频输出：3.5mm接到音箱

**Comment by wzpan** [comment]
这两个配置加了吗？

```
# wav声音播放配置
# 可选值：
# aplay         - 子进程aplay播放
# pyaudio       - pyaudio模块播放
sound_engine: aplay

# mp3文件播放配置
# 可选值：
# play          - 子进程play播放
# pygame        - pygame库播放(树莓派python默认自带，推荐配置)
# vlc           - vlc库播放(短音频可能播放有问题)
music_engine: play 
```

**Comment by calvingit** [comment]
额。。。是这个设置没加，大意了，镜像里面的profile.yml没有加两个配置，可以考虑加进去

**Comment by wzpan** [comment]
@calvingit 新版本的镜像我是加了的。你是什么版本的镜像？
