### ISSUE TITLE
File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>     import pip.req ImportError: No module named req

### ISSUE THREAD

**Issue by NeXT286** [dingdang-robot/dingdang-robot#11]
I get this error while I was starting up Dingdang at the first time
在初次启动中我遇到了这个错误

**Comment by wzpan** [comment]
```
sudo apt-get remove python-pip  # 先卸掉原来的 pip
sudo easy_install pip # 重装 pip 
```

**Comment by NeXT286** [comment]
我重装完了，但还是不行

**Comment by NeXT286** [comment]
pi@raspberrypi:~/dingdang $ python dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 32, in <module>
    from . import diagnose
  File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>
    import pip.req
ImportError: No module named req
pi@raspberrypi:~/dingdang $

这是日志

**Comment by NeXT286** [comment]
pi@raspberrypi:~/dingdang $ python dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 32, in <module>
    from . import diagnose
  File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>
    import pip.req
ImportError: No module named req
pi@raspberrypi:~/dingdang $

**Comment by wzpan** [comment]
试试把  client/diagnose.py 第 10 行改成

``` py
from pip import req
```

然后把第 108 行改成

``` py
reqs = list(req.parse_requirements(fname))
```

**Comment by NeXT286** [comment]
pi@raspberrypi:~/dingdang $ python dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 32, in <module>
    from . import diagnose
  File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>
    from pip import req
ImportError: cannot import name req

又发生这样的错误怎么办

**Comment by NeXT286** [comment]
是不是我少装了一些东西

**Comment by NeXT286** [comment]
我严格按照安装指南走了一遍

**Comment by NeXT286** [comment]
我重装了也不行，是要把代码改回来吗

**Comment by wzpan** [comment]
你试试改回去吧，不过应该和代码无关。

**Comment by NeXT286** [comment]
现在是six的问题
Pip显示six已安装但是dingdang读取不了
我对Python了解不多，请指教
是不是软连接的问题

**Comment by G10DRAS** [comment]
try
sudo python -m pip install --upgrade pip==9.0.3

**Comment by NeXT286** [comment]
感谢，安装成功了

**Comment by Lazzboys** [comment]
@NeXT286  请问到底是如何解决？看完了，没明白问题关键是哪个？

**Comment by joinfun** [comment]
我的是这样解决的  sudo python -m pip install --upgrade pip==9.0.3
 👍
