### ISSUE TITLE
执行dingdang.py报错

### ISSUE THREAD

**Issue by pjjfish123** [dingdang-robot/dingdang-robot#112]
pi@raspberrypi:~/dingdang $ python dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 16, in <module>
    from client.conversation import Conversation
  File "/home/pi/dingdang/client/conversation.py", line 8, in <module>
    from .drivers.pixels import Pixels
  File "/home/pi/dingdang/client/drivers/pixels.py", line 1, in <module>
    import RPi.GPIO as GPIO
ImportError: No module named RPi.GPIO

**Comment by wzpan** [comment]
用什么麦克风？你是不是用了 respeaker 分支但却是普通麦克风？

**Comment by pjjfish123** [comment]
麦克风测试arecord，aplay。声音录入和播放正常。
PS3原装全新摄像头PC可用Playstation3 EYE CCV可选B4版本可开发

**Comment by wzpan** [comment]
git branch 看下你的分支

**Comment by pjjfish123** [comment]
pi@raspberrypi:~/dingdang $ git branch
* master

**Comment by wzpan** [comment]
试试：

``` sh
sudo pip install RPi.GPIO
```

**Comment by pjjfish123** [comment]
python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Traceback (most recent call last):
  File "dingdang.py", line 120, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/dingd                                 ang.log'

**Comment by pjjfish123** [comment]
python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Traceback (most recent call last):
  File "dingdang.py", line 120, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/dingd                                 ang.log'

**Comment by pjjfish123** [comment]
如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Traceback (most recent call last):
  File "dingdang.py", line 120, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/dingdang.log'

**Comment by pjjfish123** [comment]
pi@raspberrypi:~/dingdang $ python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`
Traceback (most recent call last):
  File "dingdang.py", line 120, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/dingdang.log'

**Comment by pjjfish123** [comment]
> 试试：
> 
> ```shell
> sudo pip install RPi.GPIO
> ```
pi@raspberrypi:~/dingdang $ python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Traceback (most recent call last):
  File "dingdang.py", line 120, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/dingdang.log'

**Comment by pjjfish123** [comment]
pi@raspberrypi:~/dingdang $ python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Traceback (most recent call last):
  File "dingdang.py", line 120, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/ding

**Comment by pjjfish123** [comment]
pi@raspberrypi:~/dingdang $ python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Traceback (most recent call last):
  File "dingdang.py", line 120, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/ding

**Comment by pjjfish123** [comment]
![image](https://user-images.githubusercontent.com/31687043/48114968-1af77280-e29c-11e8-807a-96cbbd510606.png)

**Comment by wzpan** [comment]
明显log没给全

**Comment by wangjiwang** [comment]
请问您画皮来是怎么解决的呢？遇到了和您一样的问题，[图片]
