### ISSUE TITLE
启动异常  个个PY

### ISSUE THREAD

**Issue by callmelige** [dingdang-robot/dingdang-robot#115]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/dingdang-robot/dingdang-robot/issues) 页、[常见问题](https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting)页、[论坛](http://bbs.hahack.com) 中都查找过，没有找到类似问题。我也没有 google / bing/ 百度 / duckduckgo 到相关问题。

**安装方式**

手动安装/镜像安装

**操作系统**

（例如 Raspbian Stretch）

**问题描述**

具体说明下问题

**复现步骤**

具体描述下复现步骤

**Comment by callmelige** [comment]
2018-11-10 04:37:03,873 plugin_loader.py[line:67] INFO: plugin 'Camera' is disabled
2018-11-10 04:37:03,877 plugin_loader.py[line:67] INFO: plugin 'Email' is disabled
2018-11-10 04:37:04,317 plugin_loader.py[line:50] WARNING: Skipped plugin 'Lamp' due to an error.
Traceback (most recent call last):
  File "/home/pi/dingdang/client/plugin_loader.py", line 47, in init_plugins
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/pi/.dingdang/contrib/Lamp.py", line 5, in <module>
    import wiringpi
ImportError: No module named wiringpi
2018-11-10 04:37:04,614 plugin_loader.py[line:50] WARNING: Skipped plugin 'NetEaseMusic' due to an error.
Traceback (most recent call last):
  File "/home/pi/dingdang/client/plugin_loader.py", line 47, in init_plugins
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/pi/.dingdang/contrib/NetEaseMusic.py", line 13, in <module>
    import eyed3
ImportError: No module named eyed3
2018-11-10 04:37:04,636 mic.py[line:45] INFO: Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
2018-11-10 04:37:04,696 mic.py[line:52] INFO: Initialization of PyAudio completed.
2018-11-10 04:37:04,761 base.py[line:132] INFO: Scheduler started
2018-11-10 04:37:04,811 base.py[line:743] INFO: Added job "Notifier.gather" to job store "default"
2018-11-10 04:37:04,975 config.py[line:81] WARNING: statistic not specified in profile, defaulting to 'True'
2018-11-10 04:37:05,333 mic.py[line:351] INFO: 机器人说：主人，我能为您做什么?
2018-11-10 04:37:05,335 dingdang.py[line:145] ERROR: dingdang quit unexpectedly!
Traceback (most recent call last):
  File "dingdang.py", line 140, in <module>
    app.run()
  File "dingdang.py", line 85, in run
    self.mic.say(salutation, cache=True)
  File "/home/pi/dingdang/client/mic.py", line 360, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang/client/tts.py", line 127, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 213, in get_speech
    self.token = self.get_token()
  File "/home/pi/dingdang/client/tts.py", line 177, in get_token
    'a+')
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/baidustt.ini'
2018-11-10 04:37:05,338 base.py[line:159] INFO: Scheduler has been shut down

**Comment by wzpan** [comment]
试试手动创建个空文件：

```
touch /home/pi/dingdang/temp/baidustt.ini
```
