### ISSUE TITLE
执行dingdang.py报错 

### ISSUE THREAD

**Issue by pcCoCo** [dingdang-robot/dingdang-robot#116]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/dingdang-robot/dingdang-robot/issues) 页、[常见问题](https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting)页、[论坛](http://bbs.hahack.com) 中都查找过，没有找到类似问题。我也没有 google / bing/ 百度 / duckduckgo 到相关问题。

**安装方式**

手动安装

**操作系统**
树莓派
（例如 Raspbian Stretch）

**问题描述**

运行dingdang.py失败
具体说明下问题

查看具体文件  显示以下错误信息 cat temp/dingdang.log
2018-11-10 11:42:58,061 dingdang.py[line:135] ERROR: Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 133, in <module>
    app = Dingdang()
  File "dingdang.py", line 50, in __init__
    stt_passive_engine_class = stt.get_engine_by_slug(slug)
  File "/home/pi/dingdang/client/stt.py", line 834, in get_engine_by_slug
    raise ValueError("No STT engine found for slug '%s'" % slug)
ValueError: No STT engine found for slug 'snowboy'

**复现步骤**

具体描述下复现步骤
  
   snowboy已经安装了  导入模块也没有问题  请问还需要其他步骤才能使用吗?

**Comment by pcCoCo** [comment]
配置文件忘记写了一个关键字

**Comment by pcCoCo** [comment]
配置文件忘记写了一个关键字
