### ISSUE TITLE
设置pocketsphinx离线识别引擎, 报错

### ISSUE THREAD

**Issue by rouyunpan** [dingdang-robot/dingdang-robot#118]
**安装方式**
手动安装

**操作系统**
 Raspbian Stretch

**问题描述**
Active Listening 的 离线 SST 引擎设置 sphinx in profile.yml
stt_engine: sphinx
(设置 ali-stt -> OK)

报错
2018-11-12 17:39:23,518 vocabcompiler.py[line:163] INFO: Starting compilation...
2018-11-12 17:39:25,186 g2p.py[line:56] ERROR: Command 'phonetisaurus-g2p --model=/home/pi/g014b2b/g014b2b.fst --input=/tmp/tmp6G5bZR.g2p --words --isfile' return with exit status -11
2018-11-12 17:39:25,187 vocabcompiler.py[line:168] ERROR: Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/dingdang/client/vocabcompiler.py", line 165, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 273, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 323, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/pi/dingdang/client/g2p.py", line 128, in translate
    output = self._translate_words(words)
  File "/home/pi/dingdang/client/g2p.py", line 117, in _translate_words
    nbest=self.nbest)
  File "/home/pi/dingdang/client/g2p.py", line 57, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
2018-11-12 17:39:25,191 dingdang.py[line:135] ERROR: Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 133, in <module>
    app = Dingdang()
  File "dingdang.py", line 60, in __init__
    stt_engine_class.get_active_instance())
  File "/home/pi/dingdang/client/stt.py", line 71, in get_active_instance
    return cls.get_instance('default', phrases)
  File "/home/pi/dingdang/client/stt.py", line 58, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 173, in compile
    raise e
OSError: Command execution failed

**复现步骤**
Active Listening 的 SST 引擎设置 sphinx  in profile.yml
stt_engine: sphinx

python dingdang.py --verbose

**Comment by wzpan** [comment]
一般情况下不用走 compilation，你是不是设了一个自定义唤醒词但是没有提供字典？

**Comment by rouyunpan** [comment]
我自定义唤醒词引擎用sphinx, 有用网站产生字典, 使用是OK的
把离线 SST 引擎, 在profile.yml 是改用sphinx. 才产生这个error. 

如果离线SST 引擎要用sphinx, 要怎么设定字典?

P. S. 我觉得SST 引擎 用Ali-stt 有点慢(约4~5秒有回复 )

**Comment by rouyunpan** [comment]
我看到debug message. 如果离线 stt engine 设成sphinx.
叮当会去扫描plungin目录下的关键字words, 产生一个 languagemodel 在这个路径
/home/pi/.dingdang/vocabularies/pocketsphinx-vocabulary/default/languagemodel

这个 languagemodel 跟我唤醒词 engine 用产生的 languagemodel , 会冲突？
/home/pi/.dingdang/vocabularies/pocketsphinx-vocabulary/keyword/languagemodel
需要修改嘛？

2018-11-13 12:17:11,262 vocabcompiler.py[line:106] DEBUG: compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
2018-11-13 12:17:11,912 plugin_loader.py[line:38] DEBUG: Looking for plugins in: '/home/pi/dingdang/client/plugins', '/home/pi/.dingdang/contrib', '/home/pi/.dingdang/custom'
2018-11-13 12:17:11,924 plugin_loader.py[line:77] DEBUG: Found query plugin 'Camera' with words: [u'PAIZHAO', u'ZHAOPIAN']
2018-11-13 12:17:11,925 plugin_loader.py[line:77] DEBUG: Found query plugin 'Email' with words: ['EMAIL', 'INBOX']
2018-11-13 12:17:12,035 vocabcompiler.py[line:163] INFO: Starting compilation...
2018-11-13 12:17:12,036 vocabcompiler.py[line:270] DEBUG: Compiling languagemodel...
2018-11-13 12:17:12,037 vocabcompiler.py[line:291] DEBUG: Creating vocab file: '/tmp/tmpOyRvxV.vocab'
2018-11-13 12:17:12,641 __init__.py[line:90] DEBUG: text2wfreq : Reading text from standard input...
2018-11-13 12:17:12,642 __init__.py[line:90] DEBUG: text2wfreq : Done.
2018-11-13 12:17:12,643 __init__.py[line:111] DEBUG: Command 'text2wfreq -hash 1000000 -verbosity 2' returned with exit code '0'.
2018-11-13 12:17:12,656 __init__.py[line:90] DEBUG: wfreq2vocab : Will generate a vocabulary containing the most
2018-11-13 12:17:12,657 __init__.py[line:90] DEBUG: frequent 20000 words. Reading wfreq stream from stdin...
2018-11-13 12:17:12,657 __init__.py[line:90] DEBUG: wfreq2vocab : Done.
2018-11-13 12:17:12,658 __init__.py[line:141] DEBUG: Command 'wfreq2vocab -verbosity 2 -records 1000000' returned with exit code '0'.
2018-11-13 12:17:12,659 vocabcompiler.py[line:295] DEBUG: Creating languagemodel file: '/home/pi/.dingdang/vocabularies/pocketsphinx-vocabulary/default/languagemodel'
...
2018-11-13 12:17:13,718 __init__.py[line:90] DEBUG: idngram2lm : Done.
2018-11-13 12:17:13,720 __init__.py[line:438] DEBUG: Command 'idngram2lm -idngram /tmp/tmpMNK7XC.idngram -vocab /tmp/tmpOyRvxV.vocab -vocab_type 1 -oov_fraction 0.5 -min_unicount 0 -verbosity 2 -n 3 -arpa /home/pi/.dingdang/vocabularies/pocketsphinx-vocabulary/default/languagemodel -bin_input' returned with exit code '0'.
2018-11-13 12:17:13,722 vocabcompiler.py[line:300] DEBUG: Getting words from vocab file and removing it afterwards...
2018-11-13 12:17:13,723 vocabcompiler.py[line:272] DEBUG: Starting dictionary...
2018-11-13 12:17:13,724 vocabcompiler.py[line:321] DEBUG: Getting phonemes for 4 words...
2018-11-13 12:17:13,842 diagnose.py[line:58] DEBUG: Checking executable 'phonetisaurus-g2p'...
2018-11-13 12:17:13,842 diagnose.py[line:63] DEBUG: Executable 'phonetisaurus-g2p' found: '/usr/local/bin/phonetisaurus-g2p'
2018-11-13 12:17:13,845 g2p.py[line:99] DEBUG: Using FST model: '/home/pi/g014b2b/g014b2b.fst'
2018-11-13 12:17:13,845 g2p.py[line:127] DEBUG: Converting 4 words to phonemes
2018-11-13 12:17:14,183 g2p.py[line:52] DEBUG: ERROR: FstHeader::Read: Bad FST header: /home/pi/g014b2b/g014b2b.fst
2018-11-13 12:17:14,183 g2p.py[line:56] ERROR: Command 'phonetisaurus-g2p --model=/home/pi/g014b2b/g014b2b.fst --input=/tmp/tmpLOsRFT.g2p --words --isfile' return with exit status -11
2018-11-13 12:17:14,184 vocabcompiler.py[line:168] ERROR: Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/dingdang/client/vocabcompiler.py", line 165, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 273, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 323, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/pi/dingdang/client/g2p.py", line 128, in translate
    output = self._translate_words(words)
  File "/home/pi/dingdang/client/g2p.py", line 117, in _translate_words
    nbest=self.nbest)
  File "/home/pi/dingdang/client/g2p.py", line 57, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
2018-11-13 12:17:14,193 dingdang.py[line:135] ERROR: Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 133, in <module>
    app = Dingdang()
  File "dingdang.py", line 60, in __init__
    stt_engine_class.get_active_instance())
  File "/home/pi/dingdang/client/stt.py", line 71, in get_active_instance
    return cls.get_instance('default', phrases)
  File "/home/pi/dingdang/client/stt.py", line 58, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 173, in compile

**Comment by rouyunpan** [comment]
发现我从jasper 抓下来的g014b2b  要重新编译 CMUdict g014b2b trained model. (百度云抓不下来)
执行compile-fst.sh 产生 g014b2b.fst.

这样stt_engine 设成 sphinx, 就可以执行了离线命令

plugin 的 languagemodel 会被产生放在
/home/pi/.dingdang/vocabularies/pocketsphinx-vocabulary/default/languagemodel

keyword 的 languagemodel 
/home/pi/.dingdang/vocabularies/pocketsphinx-vocabulary/keyword/languagemodel
