### ISSUE TITLE
启动后退出问题

### ISSUE THREAD

**Issue by Roadscholar** [dingdang-robot/dingdang-robot#12]
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 125, in run
    conversation.handleForever()
  File "/home/pi/dingdang/client/conversation.py", line 67, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/dingdang/client/mic.py", line 144, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

**Comment by wzpan** [comment]
mic没配置好，arecord，aplay 能工作了再用叮当。
