### ISSUE TITLE
启动出错，直接停止

### ISSUE THREAD

**Issue by Conrad-hui** [dingdang-robot/dingdang-robot#16]
提示No handlers could be found for logger "client.vocabcompiler"
完整信息如下：
No handlers could be found for logger "client.vocabcompiler"

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`
然后停止了，我按照教程安装的，有些设备还没接入，想先试试能否运行。

**Comment by Conrad-hui** [comment]
日志为
2018-04-11 11:18:31,961 dingdang.py[line:175]             ERROR Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 173, in <module>
    app = Dingdang()
  File "dingdang.py", line 95, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/dingdang/client/stt.py", line 66, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/dingdang/client/stt.py", line 58, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 173, in compile
    raise e
NameError: global name 'cmuclmtk' is not defined

**Comment by wzpan** [comment]
手动安装？你没有装好 cmuclmtk 。

https://github.com/dingdang-robot/dingdang-robot/wiki/install

**Comment by Conrad-hui** [comment]
当我安装好后，那个错误提示没了，但还是直接退出。日志如下
2018-04-11 11:26:26,139 dingdang.py[line:175]             ERROR Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 173, in <module>
    app = Dingdang()
  File "dingdang.py", line 95, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/dingdang/client/stt.py", line 66, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/dingdang/client/stt.py", line 58, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 173, in compile
    raise e
OSError: Command execution failed

**Comment by wzpan** [comment]
你是不是自己自定义了一个robotname，然而又没有生成相应的 vocabularies ？详见修改唤醒词：https://github.com/dingdang-robot/dingdang-robot/wiki/configuration#%E4%BF%AE%E6%94%B9%E5%94%A4%E9%86%92%E8%AF%8D

**Comment by Conrad-hui** [comment]
是这样修改么
profile文件修改了这两行robot_name: 'XIAODINGDANG'  # 必须使用大写
robot_name_cn: '小叮当'
keyword添加这两行DINGDANG
XIAODINGDANG
然后按教程做了还是不行。。

**Comment by Conrad-hui** [comment]
是这样修改么
profile文件修改了这两行robot_name: 'XIAODINGDANG' # 必须使用大写
robot_name_cn: '小叮当'
keyword添加这两行DINGDANG
XIAODINGDANG
然后按教程做了还是不行。。

**Comment by wzpan** [comment]
你的XIAODINGDANG训练了vocabularies没？要到lmtool里生成词库。

**Comment by wzpan** [comment]
建议先跑起来再尝试改唤醒词

**Comment by Conrad-hui** [comment]
训练了，按教程弄的唤醒词不修改还是一样的错误

**Comment by wzpan** [comment]
你的vocabularies.zip正确解压了吗？

**Comment by Conrad-hui** [comment]
应该是正确的，我现在镜像安装了，等麦克到了看看功能能不能实现。麻烦你了。
