### ISSUE TITLE
镜像安装后运行不了，simplejson.scanner.JSONDecodeError: 

### ISSUE THREAD

**Issue by Conrad-hui** [dingdang-robot/dingdang-robot#18]
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 124, in run
    self.mic.say(salutation, cache=True)
  File "/home/pi/dingdang-robot-master/client/mic.py", line 335, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang-robot-master/client/tts.py", line 133, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang-robot-master/client/tts.py", line 313, in get_speech
    result_info = requests.post(getinfo_url, data=data).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
手动安装出现问题于是安装了镜像，麦克音响配置好后运行出错，在网上找了很久试了都不行。

**Comment by Conrad-hui** [comment]
有关配音合成的网址，比如http://www.peiyinge.com/make/getSynthSign都无效了，应该是这个原因。

**Comment by Conrad-hui** [comment]
更换百度语音后已成功。
