### ISSUE TITLE
ValueError: STT engine 'snowboy-stt' is not available

### ISSUE THREAD

**Issue by XMPST** [dingdang-robot/dingdang-robot#19]
我使用snowboy唤醒引擎，运行后提示`ValueError: STT engine 'snowboy-stt' is not available (due to missing dependencies, missing dependencies, etc.)`
请问这是什么问题，有哪位大佬帮忙解决一下吗？
```
Traceback (most recent call last):
  File "dingdang.py", line 173, in <module>
    app = Dingdang()
  File "dingdang.py", line 79, in __init__
    stt_passive_engine_class = stt.get_engine_by_slug(slug)
  File "/root/dingdang-robot/client/stt.py", line 843, in get_engine_by_slug
    "dependencies, etc.)") % slug)
ValueError: STT engine 'snowboy-stt' is not available (due to missing dependencies, missing dependencies, etc.)
```

**Comment by wzpan** [comment]
没懂为什么会这样。你改过dingdang-robot的源码吗？

**Comment by XMPST** [comment]
没有，直接git下来，然后配置好后用默认的pocketsphinx唤醒引擎可以正常使用的，可是换成snowboy唤醒引擎后重新运行就报错了

**Comment by wzpan** [comment]
我这边测试没有复现。你clone的是哪个仓库地址？`git remote -v` 看一下。另外说一下你的系统环境。

**Comment by XMPST** [comment]
用的是华硕的Tinker Board主板，系统问debian 9的

**Comment by XMPST** [comment]
snowboy-stt唤醒是否还需要特殊的设置？

**Comment by wzpan** [comment]
这里需要设置：

``` yml
# snowboy 唤醒SST引擎（可选）
# https://snowboy.kitt.ai/dashboard
snowboy:
    model: '/home/pi/dingdang/client/snowboy/dingdangdingdang.pmdl'  # 唤醒词模型
    sensitivity: "0.5"  # 敏感度
```

如果用的是默认的词就不需要改。

贴一下你的 `git remote -v` 结果。

**Comment by XMPST** [comment]
```
root@tinkerboard dingdang 17:55:05 # git remote -v
origin  https://github.com/dingdang-robot/dingdang-robot.git (fetch)
origin  https://github.com/dingdang-robot/dingdang-robot.git (push)
```

**Comment by XMPST** [comment]
应该是这里检查有问题
```
@classmethod
def is_available(cls):
    return diagnose.check_python_import('snowboy.snowboydetect')
```
在stt.py +659行，我去掉这个模块检查就可以运行了，但是还没有测试是否可以唤醒

**Comment by wzpan** [comment]
这里有问题说明找不到 snowboy.snowboydetect 模块。我怀疑你是漏了安装什么库导致加载不了 snowboy 的 so 包。

保守起见，建议你阅读 snowboy 的文档，把该装的库装上。http://docs.kitt.ai/snowboy/
