### ISSUE TITLE
TypeError: character mapping must return integer, None or unicode

### ISSUE THREAD

**Issue by godfery** [dingdang-robot/dingdang-robot#2]
请扫描如下二维码登录微信
登录成功后，可以与自己的微信账号（不是文件传输助手）交互
2018-03-21 22:51:04,324 mic.py[line:326]         INFO 机器人说：伟洲 我能为您做什么?
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 124, in run
    self.mic.say(salutation, cache=True)
2018-03-21 22:51:04,338 connectionpool.py[line:700]         INFO Starting new HTTPS connection (1): login.weixin.qq.com
  File "/home/pi/dingdang/client/mic.py", line 335, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang/client/tts.py", line 133, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 409, in get_speech
    signature = self.to_sha1_base64(stringToSign, self.ak_secret)
  File "/home/pi/dingdang/client/tts.py", line 382, in to_sha1_base64
    hmacsha1 = hmac.new(secret, stringToSign, hashlib.sha1)
  File "/usr/local/python/2.7.14/lib/python2.7/hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/python/2.7.14/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode

这个 有快速解决办法吗？

**Comment by wzpan** [comment]
更新一下dingdang试试，你用的语音服务应该是阿里的，存在可能获取不到MAC的问题，已修复。

**Comment by godfery** [comment]
@wzpan 问题解决了。
