### ISSUE TITLE
镜像安装运行后出现这个错误simplejson.scanner.JSONDecodeError:

### ISSUE THREAD

**Issue by mapenghui03** [dingdang-robot/dingdang-robot#20]
pi@raspberrypi:~/dingdang $ python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 124, in run
    self.mic.say(salutation, cache=True)
  File "/home/pi/dingdang/client/mic.py", line 338, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang/client/tts.py", line 133, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 313, in get_speech
    result_info = requests.post(getinfo_url, data=data).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by wzpan** [comment]
科大讯飞的tts出问题了，换其他tts服务试试
