### ISSUE TITLE
SnowboySTT报错，这是缺少依赖还是？

### ISSUE THREAD

**Issue by ybincn** [dingdang-robot/dingdang-robot#25]
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 125, in run
    conversation.handleForever()
  File "/home/py/dingdang/client/conversation.py", line 67, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/py/dingdang/client/mic.py", line 235, in passiveListen
    ''.join(frames))
  File "/home/py/dingdang/client/stt.py", line 652, in transcribe_keyword
    ans = self.detector.RunDetection(data)
AttributeError: 'SnowboySTT' object has no attribute 'detector'

**Comment by wzpan** [comment]
应该是缺少依赖了。建议阅读snowboy的安装教程检查一下是否都已安装。
