### ISSUE TITLE
运行python dingdang.py 出错

### ISSUE THREAD

**Issue by wong218** [dingdang-robot/dingdang-robot#37]
运行后出现以下提示，然后停止。我是用镜像安装，然后更新了下系统。不知道是不是这原因。
谁可以解答下呢？
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 124, in run
    self.mic.say(salutation, cache=True)
  File "/home/pi/dingdang/client/mic.py", line 335, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang/client/tts.py", line 133, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 313, in get_speech
    result_info = requests.post(getinfo_url, data=data).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by mcxr4299** [comment]
暂时讯飞tts不可用，换成其他的

**Comment by wzpan** [comment]
换成百度TTS试试

**Comment by wong218** [comment]
可以了，是因为讯飞问题，更换了阿里的

**Comment by lyc-changeworld** [comment]
pi@raspberrypi:~/dingdang $ python dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 32, in <module>
    from . import diagnose
  File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>
    import pip.req
ImportError: No module named req

**Comment by oldcatzhang** [comment]
@lyc-changeworld 我也是这个错误，请问你是怎么解决的呢？

**Comment by clark979899** [comment]
@lyc-changeworld @oldcatzhang 
在网上查到，直接在原函数中把import改为直接添加代码函数可解决：
def parse_requirements(filename):
    """ load requirements from a pip requirements file """
    lineiter = (line.strip() for line in open(filename))
    return [line for line in lineiter if line and not line.startswith("#")]
