### ISSUE TITLE
运行 python2 dingdang.py 报错 找不到pip.req

### ISSUE THREAD

**Issue by Lazzboys** [dingdang-robot/dingdang-robot#38]
使用镜像还原的叮当环境，开始可以使用。后续安装了python3版本和更新了软件，再次运行出现如下错误：
root@raspberrypi:/home/pi/dingdang# python2 dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 32, in <module>
    from . import diagnose
  File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>
    import pip.req
ImportError: No module named req

请问，这个问题如何解决？谢谢

**Comment by Lazzboys** [comment]
运行python3 dingdang.py或者python dingdang.py ，报错如下：

root@raspberrypi:/home/pi/dingdang# python3 dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 24, in <module>
    import md5
ImportError: No module named 'md5'
查文档发现md5在python3里面被import hashlib  取代了，
还是得去python2下面解决。

**Comment by wzpan** [comment]
1. 切仓库地址到 dingdang-robot/dingdang-robot.git。方法详见项目主页README的置顶说明。
2. git pull 更新一下工程。

**Comment by fairzhong** [comment]
pip 10版本改成import pip._internal.req这样就好了
