### ISSUE TITLE
returned with non-zero exit status '255'

### ISSUE THREAD

**Issue by godfery** [dingdang-robot/dingdang-robot#4]
INFO: ngram_search_fwdtree.c(333): Created 723 root, 152481 non-root channels, 53 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
2018-03-22 21:48:13,420 vocabcompiler.py[line:163]         INFO Starting compilation...
2018-03-22 21:48:14,926 vocabcompiler.py[line:168]         ERROR Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/dingdang/client/vocabcompiler.py", line 165, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 271, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 296, in _compile_languagemodel
    cmuclmtk.text2lm(text, output_file, vocab_file=vocab_file)
  File "/usr/local/python/2.7.14/lib/python2.7/site-packages/cmuclmtk/__init__.py", line 509, in text2lm
    output1 = text2idngram(text, vocab_file=used_vocab_file, output_file=idngram_file, **text2idngram_kwargs)
  File "/usr/local/python/2.7.14/lib/python2.7/site-packages/cmuclmtk/__init__.py", line 237, in text2idngram
    raise ConversionError("'%r' returned with non-zero exit status '%s'" % (cmd, exitcode))
ConversionError: '['text2idngram', '-vocab', '/tmp/tmpv6aFE0.vocab', '-idngram', '/tmp/tmpADdc1t.idngram', '-buffer', '100', '-hash', '2000000', '-files', '20', '-verbosity', '2', '-n', '3', '-fof_size', '10']' returned with non-zero exit status '255'

启动的时候出现了错误，不知道是那个地方出现问题了。
请帮忙看一下。

**Comment by godfery** [comment]
是我环境装乱了。
