### ISSUE TITLE
没有任何声音，报错 simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

### ISSUE THREAD

**Issue by yusanshi** [dingdang-robot/dingdang-robot#41]
启动报错如下：
<pre>root@raspberrypi:/home/pi/dingdang# python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`

{'url': 'http://api.musiiot.top/stt.php', 'api_key': 'fdf9e712f40942d796f56d1772b426f2', 'api_id': '5a90293c', 'vid': '65360'}
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
请扫描如下二维码登录微信
登录成功后，可以与自己的微信账号（不是文件传输助手）交互
Traceback (most recent call last):
  File "dingdang.py", line 135, in <module>
    app.run()
  File "dingdang.py", line 81, in run
    self.mic.say(salutation, cache=True)
  File "/home/pi/dingdang/client/mic.py", line 331, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang/client/tts.py", line 134, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 294, in get_speech
    result_info = requests.post(getinfo_url, data=data).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 797, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 2)</pre>

微信二维码显示正常，微信登录也正常。
微信里发完消息报错日志如下：
<pre>[MSG] self:
    [Text] 嘿
[ERROR] Except in proc_msg
Traceback (most recent call last):
  File "/home/pi/dingdang/client/wxbot.py", line 822, in proc_msg
    res = self.check_msg()
  File "/home/pi/dingdang/client/wxbot.py", line 787, in check_msg
    self.handle_msg(r)
  File "/home/pi/dingdang/client/wxbot.py", line 767, in handle_msg
    self.handle_msg_all(message)
  File "/home/pi/dingdang/client/WechatBot.py", line 35, in handle_msg_all
    profile = self.brain.profile
AttributeError: 'Brain' object has no attribute 'profile'
</pre>

硬件：树莓派3B + ReSpeaker 2-Mics Pi HAT ，
软件：dingdang-respeaker-2017-11-07版本，
Respeaker配置正常，`arecord -f cd -Dhw:1 | aplay -Dhw:1` 命令正常。
求助。

**Comment by wzpan** [comment]
见 #37
