### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hmm'

### ISSUE THREAD

**Issue by Seanseattle** [dingdang-robot/dingdang-robot#44]
启动dingdang的时候发现了这个错误，
2018-05-15 13:15:43,718 dingdang.py[line:132] ERROR: Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 130, in <module>
    app = Dingdang()
  File "dingdang.py", line 58, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/sean/PycharmProjects/dingdang-robot/client/stt.py", line 66, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/sean/PycharmProjects/dingdang-robot/client/stt.py", line 60, in get_instance
    instance = cls(**config)
  File "/home/sean/PycharmProjects/dingdang-robot/client/stt.py", line 152, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'
我使用的pocketsphinx 0.8的
有谁知道怎么解决吗

**Comment by wzpan** [comment]
在 pocketsphinx 里补上 `hmm_dir` 即可解决。
