### ISSUE TITLE
pyhton dingdang.py  报错

### ISSUE THREAD

**Issue by vivid-marryme** [dingdang-robot/dingdang-robot#46]
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 125, in run
    conversation.handleForever()
  File "/home/pi/dingdang/client/conversation.py", line 67, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/dingdang/client/mic.py", line 144, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

求指导

**Comment by wzpan** [comment]
arecord，aplay 能否正常工作？

**Comment by zhyjor** [comment]
相同的问题，我也遇到了

**Comment by vivid-marryme** [comment]
你先看看配置。 看录音 和 播放好着么 


发自网易邮箱大师
在2018年06月11日 19:52，godmeir 写道：

相同的问题，我也遇到了

**Comment by zhyjor** [comment]
我试了录音和播放都是正常的

**Comment by zhyjor** [comment]
启动的时候，会播放那句“能为你做什么”,然后就报错了
