### ISSUE TITLE
pyhton dingdang.py 报错

### ISSUE THREAD

**Issue by Ecalpal** [dingdang-robot/dingdang-robot#47]
pi@raspberrypi:~/dingdang $ python dingdang.py
Traceback (most recent call last):
  File "dingdang.py", line 16, in <module>
    from client.conversation import Conversation
  File "/home/pi/dingdang/client/conversation.py", line 7, in <module>
    from .drivers.pixels import pixels
  File "/home/pi/dingdang/client/drivers/pixels.py", line 124, in <module>
    pixels = Pixels()
  File "/home/pi/dingdang/client/drivers/pixels.py", line 21, in __init__
    self.dev = apa102.APA102(num_led=self.PIXELS_N)
  File "/home/pi/dingdang/client/drivers/apa102.py", line 90, in __init__
    self.spi.open(bus, device)  # Open SPI port 0, slave device (CS) 1
IOError: [Errno 2] No such file or directory

请问这是什么问题。。树莓派3B。镜像安装。usb麦克风。3.5mm输出。执行过upgrade。
pcm.!default {
        type asym
            playback.pcm {
                type plug
                slave.pcm "hw:0,0"
            }
            capture.pcm {
                type plug
                slave.pcm "hw:1,0"
            }
}
ctl.!default {
        type hw
        card 2
}
arecord，aplay 均正常工作

**Comment by wzpan** [comment]
你是不是切到 respeaker 分支去了？装的镜像是 respeaker 镜像？

**Comment by Ecalpal** [comment]
似乎是的。十分感谢！我将下载dingdang-2017-10-29.img.gz再试试。
