### ISSUE TITLE
镜像安装dingdang-2017-10-29后启动失败

### ISSUE THREAD

**Issue by Ecalpal** [dingdang-robot/dingdang-robot#51]
```
pi@Mirror:~/dingdang $ python dingdang.py 

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 124, in run
    self.mic.say(salutation, cache=True)
  File "/home/pi/dingdang/client/mic.py", line 335, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang/client/tts.py", line 133, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 313, in get_speech
    result_info = requests.post(getinfo_url, data=data).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
pi@Mirror:~/dingdang $ tail -f /home/pi/dingdang/temp/dingdang.log
2018-05-22 18:14:20,605 mic.py[line:47]             INFO Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
2018-05-22 18:14:20,651 mic.py[line:54]             INFO Initialization of PyAudio completed.
2018-05-22 18:14:20,747 base.py[line:132]             INFO Scheduler started
2018-05-22 18:14:20,792 base.py[line:743]             INFO Added job "Notifier.gather" to job store "default"
2018-05-22 18:14:20,793 mic.py[line:326]             INFO 机器人说：伟洲 我能为您做什么?
2018-05-22 18:14:20,940 base.py[line:159]             INFO Scheduler has been shut down
```

arecord，aplay可以工作。
/home/pi/.dingdang/profile.yml未修改（因为我看见似乎讯飞的API KEY您已经写进去了）
镜像写入TF卡后DISENABLE了VNC SPI，安装了XRDP GEDIT，其他未做修改。

= =现在两张TF卡。。一张手动安装一张镜像DINGDANG都不能工作。。请您帮忙看看。。

**Comment by wzpan** [comment]
使用百度或者阿里的TTS。如果依然希望用讯飞的TTS，讯飞的接口需要补充新的配置：

```
# 讯飞语音服务
# api_id 及 api_key 需前往
# http://aiui.xfyun.cn/webApi
# 注册获取（注意创建的是WebAPI应用），仅使用语音合成无需注册
# 然后将主板的ip地址添加进ip白名单（建议使用中转服务器的ip地址 101.132.139.80）
iflytek_yuyin:
    api_id: '填写你的讯飞应用的Api ID'
    api_key: '填写你的讯飞应用的Api Key'  # 没看到这个说明不是注册的WebAPI应用，请改注册个WebAPI应用
    vid: '67100' #语音合成选项： 60120为小桃丸 67100为颖儿 60170为萌小新 更多音色见wiki
    url: 'http://api.musiiot.top/stt.php' # 白名单ip中转服务器（可选）
    tts:
        api_id: '***' # 这项不填可以使用上层配置
        api_key: '**********************'
        voice_name: xiaoyan
        proxy: 'http://123.207.49.217:8028' 
```

**Comment by Ecalpal** [comment]
谢谢！换百度后已可运行。
