### ISSUE TITLE
dingdang-robot/client/drivers/pixels.py 里面 import RPi.GPIO 非树莓派直接GG

### ISSUE THREAD

**Issue by zanjie1999** [dingdang-robot/dingdang-robot#58]
然后我把所有GPIO都注释掉,问题解决

另外还有一个error
这些问题的产生主要是晚上无聊git pull更新了一下

[MSG] self:
    [Text] 测试
[ERROR] Except in proc_msg
Traceback (most recent call last):
  File "/home/sparkle/dingdang-robot/client/wxbot.py", line 822, in proc_msg
    res = self.check_msg()
  File "/home/sparkle/dingdang-robot/client/wxbot.py", line 787, in check_msg
    self.handle_msg(r)
  File "/home/sparkle/dingdang-robot/client/wxbot.py", line 767, in handle_msg
    self.handle_msg_all(message)
  File "/home/sparkle/dingdang-robot/client/WechatBot.py", line 35, in handle_msg_all
    profile = self.brain.profile
AttributeError: 'Brain' object has no attribute 'profile'

**Comment by zanjie1999** [comment]
另外的问题 
无论怎么设置 robot_name 和 snowboy 的 model 
当喊出配置的 model 对应的唤醒词后,识别到的都是 DINGDANG
避开这个问题的方式就是临时把 robot_name 改成 DINGDANG
至于是哪行代码有问题我没去查

...........
2018-06-06 22:52:55,163 conversation.py[line:58] INFO: Starting to handle conversation with keyword 'XIAOGUAI'.
2018-06-06 22:53:00,598 conversation.py[line:81] INFO: Nothing has been said or transcribed.
2018-06-06 22:53:04,329 conversation.py[line:81] INFO: Nothing has been said or transcribed.
2018-06-06 22:53:07,522 conversation.py[line:81] INFO: Nothing has been said or transcribed.
2018-06-06 22:53:10,808 conversation.py[line:81] INFO: Nothing has been said or transcribed.
2018-06-06 22:53:14,133 conversation.py[line:81] INFO: Nothing has been said or transcribed.
2018-06-06 22:53:18,768 conversation.py[line:81] INFO: Nothing has been said or transcribed.
2018-06-06 22:53:20,936 conversation.py[line:81] INFO: Nothing has been said or transcribed.
2018-06-06 22:53:25,559 stt.py[line:586] INFO: snowboy 识别到了: 'DINGDANG'
2018-06-06 22:53:25,560 conversation.py[line:83] INFO: Keyword 'DINGDANG' has been said!
2018-06-06 22:53:27,151 connectionpool.py[line:700] INFO: Starting new HTTPS connection (1): nlsapi.aliyun.com
............

**Comment by zanjie1999** [comment]
对了按 Ctrl +4 可以直接把dingdang关掉的不用ps -ef 找pid在kill

**Comment by wzpan** [comment]
> 另外的问题
> 无论怎么设置 robot_name 和 snowboy 的 model
> 当喊出配置的 model 对应的唤醒词后,识别到的都是 DINGDANG
> 避开这个问题的方式就是临时把 robot_name 改成 DINGDANG

snowboy 是不管你设置了什么robot_name的，只要识别到pmdl模型对应的语音，就一律认为识别到了 robot_name 。所以不是问题。

**Comment by zanjie1999** [comment]
我再去翻代码看看吧

另外 WechatBot.py 的 35行 self .brain.profile 取不到

没搞明白是什么问题, 报错在上面
