### ISSUE TITLE
IOError: [Errno -9997] Invalid sample rate

### ISSUE THREAD

**Issue by zhyjor** [dingdang-robot/dingdang-robot#64]
dingdang-2017-10-29.img版本
aplay,arecord录制播放正常，使用的是usb语音和音响一体的设备

在root账户下python dingdang.py直接报错，完整错误如下

```
root@raspberrypi:/home/pi/dingdang# python dingdang.py 

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 125, in run
    conversation.handleForever()
  File "/home/pi/dingdang/client/conversation.py", line 67, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/dingdang/client/mic.py", line 144, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate

```

**Comment by wzpan** [comment]
似乎还是和录音有关。arecord是否无需带参数就可以录？

**Comment by wzpan** [comment]
这是因为你在root账户下启动了叮当创建了文件，这些文件的owner是root账户。又尝试在非root里启动，这些临时文件又不允许被非root账户使用。可以阅读wiki里的常见问题解答里关于dingdang.log的问题解答。
