### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by pouduo** [dingdang-robot/dingdang-robot#66]
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
** dingdang quit unexpectedly! ** 
Traceback (most recent call last):
  File "dingdang.py", line 137, in <module>
    app.run()
  File "dingdang.py", line 71, in run
    conversation = Conversation(persona, self.mic)
  File "/home/pi/dingdang/client/conversation.py", line 24, in __init__
    if signal_led_profile['enable'] and \
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by wzpan** [comment]
@pouduo 试试在 ~/.dingdang/profile.yml 里增加如下配置：

``` yaml
# 信号灯(可选)
# 将普通led接入树莓派GPIO， 唤醒后常亮，思考及说话时闪亮
signal_led:
    enable: false
    gpio_mode: "bcm" # "bcm" 或 "board"
    pin: 24 # led 正极接脚， 负极接GND
```
