### ISSUE TITLE
 ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by mapenghui03** [dingdang-robot/dingdang-robot#7]
Traceback (most recent call last):
  File "dingdang.py", line 12, in <module>
    from client import stt
  File "/home/pi/dingdang/client/stt.py", line 18, in <module>
    from . import vocabcompiler
  File "/home/pi/dingdang/client/vocabcompiler.py", line 21, in <module>
    from . import brain
ValueError: bad marshal data (unknown type code)
这个错误怎么解决一开始可以用后来安装homeassistant就出现这个错误

**Comment by wzpan** [comment]
应该和 homeassistant 无关，只是你可能 python2 和 python3 混用了。目前 dingdang 只能使用 python2 执行。
