### ISSUE TITLE
运行叮当报错

### ISSUE THREAD

**Issue by mukgong** [dingdang-robot/dingdang-robot#73]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/dingdang-robot/dingdang-robot/issues) 页、[常见问题](https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting)页、[论坛](http://bbs.hahack.com) 中都查找过，没有找到类似问题。我也没有 google / bing/ 百度 / duckduckgo 到相关问题。

** 安装方式 **
手动安装
手动安装/镜像安装

** 操作系统 **

（例如 Raspbian Stretch）

** 问题描述 **
 python ~/dingdang/dingdang.py
Traceback (most recent call last):
  File "/home/pi/dingdang/dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 32, in <module>
    from . import diagnose
  File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>
    import pip.req
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
pi@raspberrypi:~/.dingdang$ 

** 复现步骤 **
 python ~/dingdang/dingdang.py
Traceback (most recent call last):
  File "/home/pi/dingdang/dingdang.py", line 11, in <module>
    from client import tts
  File "/home/pi/dingdang/client/tts.py", line 32, in <module>
    from . import diagnose
  File "/home/pi/dingdang/client/diagnose.py", line 10, in <module>
    import pip.req
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
pi@raspberrypi:~/.dingdang$ 
具体描述下复现步骤

**Comment by mukgong** [comment]
谢谢！
