### ISSUE TITLE
叮当无法播放声音 

### ISSUE THREAD

**Issue by mukgong** [dingdang-robot/dingdang-robot#74]
问题：
启动时候和阿里云无法播放出声音。
测试：

1. 使用 aplay temp.wav 正常播放声音。
2. 下面是运行日志，那些什么都是无法从播放器播放出来，只是听到滴滴声音，没有其他响应。
3. 百度合成声音日志文件和阿里云日志，
4. 百度云提示验证失败。但是百度云日志显示调用成功。

2018-07-09 10:11:15,741 mic.py[line:326]             INFO 机器人说：什么?
2018-07-09 10:11:15,752 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): tsn.baidu.com
2018-07-09 10:11:15,844 tts.py[line:260]             CRITICAL Baidu TTS failed with response: u'authentication failed.'
None
2018-07-09 10:11:18,910 stt.py[line:220]             INFO PocketSphinx 识别到了：['HEYDINGDANG']
2018-07-09 10:11:18,912 conversation.py[line:74]             INFO Keyword 'DINGDANG' has been said!
2018-07-09 10:11:20,546 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): vop.baidu.com
2018-07-09 10:11:21,351 stt.py[line:347]             INFO 百度语音识别到了: 
2018-07-09 10:11:21,353 mic.py[line:326]             INFO 机器人说：什么?
2018-07-09 10:11:21,364 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): tsn.baidu.com
2018-07-09 10:11:21,469 tts.py[line:260]             CRITICAL Baidu TTS failed with response: u'authentication failed.'
None
2018-07-09 10:11:25,057 stt.py[line:220]             INFO PocketSphinx 识别到了：['XIAOMEI XIAOMEI']
2018-07-09 10:11:25,058 conversation.py[line:72]             INFO Nothing has been said or transcribed.
2018-07-09 10:11:29,792 stt.py[line:220]             INFO PocketSphinx 识别到了：['HEYDINGDANG']
2018-07-09 10:11:29,793 conversation.py[line:74]             INFO Keyword 'DINGDANG' has been said!
2018-07-09 10:11:32,188 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): vop.baidu.com
2018-07-09 10:11:33,613 stt.py[line:347]             INFO 百度语音识别到了: 怎么样子，
2018-07-09 10:11:33,626 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): www.tuling123.com
2018-07-09 10:11:34,130 mic.py[line:326]             INFO 机器人说：http://m.image.so.com/i?q=%E6%80%8E%E4%B9%88
2018-07-09 10:11:34,141 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): tsn.baidu.com
2018-07-09 10:11:34,237 tts.py[line:260]             CRITICAL Baidu TTS failed with response: u'authentication failed.'
None
2018-07-09 10:11:38,570 stt.py[line:220]             INFO PocketSphinx 识别到了：['']
2018-07-09 10:11:38,571 conversation.py[line:72]             INFO Nothing has been said or transcribed.
2018-07-09 10:11:42,951 stt.py[line:220]             INFO PocketSphinx 识别到了：['XIAOMEI XIAOMEI']
2018-07-09 10:11:42,952 conversation.py[line:72]             INFO Nothing has been said or transcribed.
2018-07-09 10:11:48,506 stt.py[line:220]             INFO PocketSphinx 识别到了：['HEYDINGDANG']
2018-07-09 10:11:48,507 conversation.py[line:74]             INFO Keyword 'DINGDANG' has been said!
2018-07-09 10:11:51,468 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): vop.baidu.com
2018-07-09 10:11:53,130 stt.py[line:347]             INFO 百度语音识别到了: 广州的天气情况，
2018-07-09 10:11:53,134 mic.py[line:326]             INFO 机器人说：天气插件配置有误，插件使用失败
2018-07-09 10:11:53,145 connectionpool.py[line:188]             INFO Starting new HTTP connection (1): tsn.baidu.com
2018-07-09 10:11:53,238 tts.py[line:260]             CRITICAL Baidu TTS failed with response: u'authentication f

阿里云日志
2018-07-09 10:13:08,080 base.py[line:159]             INFO Scheduler has been shut down
tail: /home/pi/dingdang/temp/dingdang.log: file truncated
2018-07-09 10:13:55,687 brain.py[line:55]             WARNING Skipped plugin 'Lamp' due to an error.
Traceback (most recent call last):
  File "/home/pi/dingdang/client/brain.py", line 52, in get_plugins
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/pi/.dingdang/contrib/Lamp.py", line 5, in <module>
    import wiringpi
ImportError: No module named wiringpi
2018-07-09 10:13:56,690 mic.py[line:47]             INFO Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
2018-07-09 10:13:56,759 mic.py[line:54]             INFO Initialization of PyAudio completed.
2018-07-09 10:13:56,797 brain.py[line:55]             WARNING Skipped plugin 'Lamp' due to an error.
Traceback (most recent call last):
  File "/home/pi/dingdang/client/brain.py", line 52, in get_plugins
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/pi/.dingdang/contrib/Lamp.py", line 5, in <module>
    import wiringpi
ImportError: No module named wiringpi
2018-07-09 10:13:56,943 base.py[line:132]             INFO Scheduler started
2018-07-09 10:13:57,027 base.py[line:743]             INFO Added job "Notifier.gather" to job store "default"
2018-07-09 10:13:57,028 mic.py[line:326]             INFO 机器人说：**  我能为您做什么?
2018-07-09 10:13:57,029 tts.py[line:130]             INFO found speech in cache, playing...[/home/pi/dingdang/temp/ali-ttsd520f32bee65403d62dbd35ce539541d.mp3]
2018-07-09 10:13:58,081 conversation.py[line:49]             INFO Starting to handle conversation with keyword 'DINGDANG'.
2018-07-09 10:14:06,599 stt.py[line:220]             INFO PocketSphinx 识别到了：['']
2018-07-09 10:14:06,603 conversation.py[line:72]             INFO Nothing has been said or transcribed.
2018-07-09 10:14:10,820 stt.py[line:220]             INFO PocketSphinx 识别到了：['']
2018-07-09 10:14:10,821 conversation.py[line:72]             INFO Nothing has been said or transcribed.

**Comment by wzpan** [comment]
`Baidu TTS failed with response: u'authentication failed.'`

说明你的百度 TTS 认证失败了，导致没法说话。可能是因为你用的是我的镜像提供的公用百度的 appkey 和 appsecret，而因为太多人用已经超出了当日的执行次数。

建议自己申请百度的 key。

**Comment by mukgong** [comment]
我用的是自己的百度key。我在百度云查到调用成功日志，就是无法播放声音。测试都要正常。

**Comment by wzpan** [comment]
@mukgong 你的应用开启语音合成的能力没？

**Comment by mukgong** [comment]
@wzpan 确定检查了百度后台没有开启语音合成。谢谢！
