### ISSUE TITLE
运行dingdang.py出错

### ISSUE THREAD

**Issue by ChaoAbner** [dingdang-robot/dingdang-robot#75]
File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 114,$
    raise ConversionError("'%s' returned with non-zero exit status '%s'" % (cmd$
ConversionError: 'text2wfreq' returned with non-zero exit status '127'
2018-07-14 16:57:11,047 dingdang.py[line:175]             ERROR Error occured!
Traceback (most recent call last):
  File "dingdang.py", line 173, in <module>
    app = Dingdang()
  File "dingdang.py", line 95, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/dingdang/client/stt.py", line 66, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/dingdang/client/stt.py", line 58, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/dingdang/client/vocabcompiler.py", line 173, in compile
    raise e
ConversionError: 'text2wfreq' returned with non-zero exit status '127'

请问出现这个是什么问题

**Comment by 18736075818** [comment]
这个问题解决了吗，我也遇到了，求助！！
