### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hmm'

### ISSUE THREAD

**Issue by redstonee** [dingdang-robot/dingdang-robot#83]
2018-07-29 15:32:09,725 dingdang.py[line:175]             ERROR Error occured!
Traceback (most recent call last):
  File "./dingdang.py", line 173, in <module>
    app = Dingdang()
  File "./dingdang.py", line 95, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/root/dingdang/client/stt.py", line 67, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/root/dingdang/client/stt.py", line 61, in get_instance
    instance = cls(**config)
  File "/root/dingdang/client/stt.py", line 153, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'

**Comment by redstonee** [comment]
What happened?

**Comment by wzpan** [comment]
应该是 hmm_dir 目录没有配置好

**Comment by Yaque** [comment]
是否解决了？

**Comment by redstonee** [comment]
没有哇
