### ISSUE TITLE
网易云音乐插件运行KeyError: u'data'错误

### ISSUE THREAD

**Issue by codywon** [dingdang-robot/dingdang-robot#98]
我已确认在 [Github issue](https://github.com/dingdang-robot/dingdang-robot/issues) 页、[常见问题](https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting)页、[论坛](http://bbs.hahack.com) 中都查找过，没有找到类似问题。我也没有 google / bing/ 百度 / duckduckgo 到相关问题。

**安装方式**

  镜像安装

**操作系统**

 raspiberry stretch

**问题描述**

网易云音乐插件无法播放，网易云音乐也是通过手机注册且提示登录成功，但运行后报错

具体说明下问题

日志如下:
2018-08-15 09:14:37,278 plugin_loader.py[line:67] INFO: plugin 'Email' is disabled
2018-08-15 09:14:38,195 mic.py[line:45] INFO: Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
2018-08-15 09:14:38,254 mic.py[line:52] INFO: Initialization of PyAudio completed.
2018-08-15 09:14:38,256 config.py[line:81] WARNING: sound_engine not specified in profile, defaulting to 'pyaudio'
2018-08-15 09:14:38,378 base.py[line:132] INFO: Scheduler started
2018-08-15 09:14:38,464 base.py[line:743] INFO: Added job "Notifier.gather" to job store "default"
2018-08-15 09:14:38,731 config.py[line:81] WARNING: statistic not specified in profile, defaulting to 'True'
2018-08-15 09:14:38,850 mic.py[line:351] INFO: 机器人说：您好，我能为您做什么?
2018-08-15 09:14:38,851 tts.py[line:124] INFO: found speech in cache, playing...[/home/pi/dingdang/temp/baidu-tts023b4f3affe25cb0c448d3f7439f5bb9.mp3]
2018-08-15 09:14:38,852 config.py[line:81] WARNING: music_engine not specified in profile, defaulting to 'play'
2018-08-15 09:14:39,909 conversation.py[line:59] INFO: Starting to handle conversation with keyword 'HEYDINGDANG'.
2018-08-15 09:14:46,199 stt.py[line:207] INFO: PocketSphinx 识别到了：['HEYDINGDANG']
2018-08-15 09:14:46,200 conversation.py[line:84] INFO: Keyword 'HEYDINGDANG' has been said!
2018-08-15 09:14:46,460 config.py[line:81] WARNING: statistic not specified in profile, defaulting to 'True'
2018-08-15 09:14:54,774 stt.py[line:321] INFO: 百度语音识别到了: 音乐，
2018-08-15 09:14:56,030 NetEaseMusic.py[line:311] INFO: 离线唤醒监听中
2018-08-15 09:14:56,063 api.py[line:106] DEBUG: {"csrf_token": "a69bb6cc0bd799ea905303efa501ff4f", "ids": [1296583188], "br": 320000}
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/home/pi/.dingdang/contrib/NetEaseMusic.py", line 499, in run
self.play()
File "/home/pi/.dingdang/contrib/NetEaseMusic.py", line 520, in play
[song['song_id']])[0]['url']
File "/usr/local/lib/python2.7/dist-packages/MusicBoxApi/api.py", line 551, in songs_detail_new_api
return result['data']
KeyError: u'data'

2018-08-15 09:15:06,611 NetEaseMusic.py[line:318] INFO: Nothing has been said or transcribed.
2018-08-15 09:15:06,612 NetEaseMusic.py[line:311] INFO: 离线唤醒监听中
2018-08-15 09:15:09,339 stt.py[line:207] INFO: PocketSphinx 识别到了：['']
2018-08-15 09:15:09,340 NetEaseMusic.py[line:318] INFO: Nothing has been said or transcribed.
2018-08-15 09:15:09,341 NetEaseMusic.py[line:311] INFO: 离线唤醒监听中
2018-08-15 09:15:11,395 stt.py[line:207] INFO: PocketSphinx 识别到了：['']
2018-08-15 09:15:11,396 NetEaseMusic.py[line:318] INFO: Nothing has been said or transcribed.
2018-08-15 09:15:11,397 NetEaseMusic.py[line:311] INFO: 离线唤醒监听中
2018-08-15 09:15:14,065 stt.py[line:207] INFO: PocketSphinx 识别到了：['HEYDINGDANG']
2018-08-15 09:15:22,036 stt.py[line:321] INFO: 百度语音识别到了: 退出播放，
2018-08-15 09:15:22,038 mic.py[line:351] INFO: 机器人说：结束播放
2018-08-15 09:15:22,039 tts.py[line:124] INFO: found speech in cache, playing...[/home/pi/dingdang/temp/baidu-tts224be4a2887086d65e2c763bf52193a6.mp3]
**复现步骤**

具体描述下复现步骤

**Comment by wzpan** [comment]
网易云音乐的api已经挂了，短期内暂时先用本地音乐吧。
